{
 "title": "Dashboard Basculas",
 "tags": [
  "iot",
  "basculas"
 ],
 "time": { "to": "now", "from": "now-2y" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ultimo peso",
   "type": "stat",
   "gridPos": { "y": 0, "w": 8, "x": 0, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "kg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT weight FROM scale_events WHERE $__timeFilter(\"timestamp\") ORDER BY \"timestamp\" DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Peso por tiempo",
   "type": "timeseries",
   "gridPos": { "y": 0, "w": 16, "x": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "kg" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS time, weight FROM scale_events WHERE $__timeFilter(\"timestamp\") ORDER BY \"timestamp\";"
    }
   ]
  },
  {
   "title": "Total de pesajes",
   "type": "stat",
   "gridPos": { "y": 7, "w": 8, "x": 0, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total FROM scale_events;"
    }
   ]
  },
  {
   "title": "Ultimos pesajes",
   "type": "table",
   "gridPos": { "y": 8, "w": 16, "x": 8, "h": 9 },
   "targets": [
    {
     "rawSql": "SELECT id, truck_plate, weight, \"timestamp\" FROM scale_events ORDER BY \"timestamp\" DESC LIMIT 20;"
    }
   ]
  }
 ]
}