{
 "title": "Dashboard Secaderos",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Temperatura por tiempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iot_db",
     "rawSql": "SELECT\r\n  \"timestamp\" AT TIME ZONE 'Europe/Madrid' AS time,\r\n  temperature\r\nFROM telemetry\r\nWHERE $__timeFilter(\"timestamp\" AT TIME ZONE 'Europe/Madrid')\r\nORDER BY \"timestamp\";"
    }
   ]
  },
  {
   "title": "Humedad por tiempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iot_db",
     "rawSql": "SELECT\r\n  \"timestamp\" AT TIME ZONE 'Europe/Madrid' AS time,\r\n  humidity\r\nFROM telemetry\r\nWHERE $__timeFilter(\"timestamp\" AT TIME ZONE 'Europe/Madrid')\r\nORDER BY \"timestamp\";"
    }
   ]
  },
  {
   "title": "Temperatura y humedad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iot_db",
     "rawSql": "SELECT\r\n  \"timestamp\" AT TIME ZONE 'Europe/Madrid' AS time,\r\n  temperature,\r\n  humidity\r\nFROM telemetry\r\nWHERE $__timeFilter(\"timestamp\" AT TIME ZONE 'Europe/Madrid')\r\nORDER BY \"timestamp\";"
    }
   ]
  },
  {
   "title": "Última temperatura",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iot_db",
     "rawSql": "SELECT\r\n  temperature\r\nFROM telemetry\r\nWHERE $__timeFilter(\"timestamp\" AT TIME ZONE 'Europe/Madrid')\r\nORDER BY \"timestamp\" DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Última humedad",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iot_db",
     "rawSql": "SELECT\r\n  humidity\r\nFROM telemetry\r\nWHERE $__timeFilter(\"timestamp\" AT TIME ZONE 'Europe/Madrid')\r\nORDER BY \"timestamp\" DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Últimas mediciones",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "iot_db",
     "rawSql": "SELECT\r\n  device_id,\r\n  temperature,\r\n  humidity,\r\n  \"timestamp\" AT TIME ZONE 'Europe/Madrid' AS timestamp\r\nFROM telemetry\r\nWHERE $__timeFilter(\"timestamp\" AT TIME ZONE 'Europe/Madrid')\r\nORDER BY \"timestamp\" DESC\r\nLIMIT 10;"
    }
   ]
  }
 ]
}